[package]
name = "anchor-layout-issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = { version = "0.30.1", features = ["derive"] }
solana-client = "2.0.3"
solana-sdk = "2.0.3"
